/**
 * @struktos/cli - Configuration File Generators
 */

import { ProjectConfig, ADAPTERS } from '../types';

/**
 * Generate .env.example file
 */
export function generateEnvExample(config: ProjectConfig): string {
  const adapterInfo = ADAPTERS[config.framework];
  const isGrpc = config.framework === 'grpc';

  let envContent = `# ${config.name} Environment Configuration
# Generated by @struktos/cli

# Application
NODE_ENV=development
`;

  if (isGrpc) {
    envContent += `GRPC_PORT=${adapterInfo.defaultPort}
GRPC_HOST=0.0.0.0
`;
  } else {
    envContent += `PORT=${adapterInfo.defaultPort}
HOST=0.0.0.0
`;
  }

  if (config.useAuth) {
    envContent += `
# Authentication
JWT_SECRET=your-secret-key-change-in-production
JWT_EXPIRES_IN=1h
`;
  }

  if (config.persistence === 'postgresql') {
    envContent += `
# PostgreSQL
DATABASE_URL=postgresql://user:password@localhost:5432/${config.name}?schema=public
`;
  } else if (config.persistence === 'mongodb') {
    envContent += `
# MongoDB
MONGODB_URI=mongodb://localhost:27017/${config.name}
`;
  }

  return envContent;
}

/**
 * Generate .gitignore file
 */
export function generateGitignore(): string {
  return `# Dependencies
node_modules/

# Build output
dist/
build/

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp
*.swo

# Logs
logs/
*.log
npm-debug.log*

# Test coverage
coverage/

# Generated files
*.generated.*

# OS
.DS_Store
Thumbs.db

# Prisma
prisma/*.db
prisma/*.db-journal
`;
}

/**
 * Generate Dockerfile
 */
export function generateDockerfile(config: ProjectConfig): string {
  const adapterInfo = ADAPTERS[config.framework];
  const isGrpc = config.framework === 'grpc';
  const port = adapterInfo.defaultPort;

  return `# ${config.name} Dockerfile
# Generated by @struktos/cli

# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build application
RUN npm run build

# Production stage
FROM node:20-alpine AS production

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install production dependencies only
RUN npm ci --production

# Copy built application
COPY --from=builder /app/dist ./dist
${isGrpc ? 'COPY --from=builder /app/protos ./protos' : ''}

# Set environment
ENV NODE_ENV=production
${isGrpc ? `ENV GRPC_PORT=${port}` : `ENV PORT=${port}`}

# Expose port
EXPOSE ${port}

# Run application
CMD ["node", "dist/main.js"]
`;
}

/**
 * Generate docker-compose.yml
 */
export function generateDockerCompose(config: ProjectConfig): string {
  const adapterInfo = ADAPTERS[config.framework];
  const isGrpc = config.framework === 'grpc';
  const port = adapterInfo.defaultPort;

  let compose = `# ${config.name} Docker Compose
# Generated by @struktos/cli

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${port}:${port}"
    environment:
      - NODE_ENV=production
`;

  if (isGrpc) {
    compose += `      - GRPC_PORT=${port}
`;
  } else {
    compose += `      - PORT=${port}
`;
  }

  if (config.useAuth) {
    compose += `      - JWT_SECRET=\${JWT_SECRET}
`;
  }

  if (config.persistence === 'postgresql') {
    compose += `      - DATABASE_URL=postgresql://postgres:postgres@db:5432/${config.name}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${config.name}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
`;
  } else if (config.persistence === 'mongodb') {
    compose += `      - MONGODB_URI=mongodb://db:27017/${config.name}
    depends_on:
      - db

  db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
`;
  }

  return compose;
}

/**
 * Generate project README
 */
export function generateReadme(config: ProjectConfig): string {
  const adapterInfo = ADAPTERS[config.framework];
  const isGrpc = config.framework === 'grpc';
  const port = adapterInfo.defaultPort;

  let readme = `# ${config.name}

> Built with [Struktos.js](https://github.com/struktosjs) - Enterprise-grade Node.js framework

## 🚀 Quick Start

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev
\`\`\`

`;

  if (isGrpc) {
    readme += `The gRPC server will start at \`grpc://localhost:${port}\`

## 📡 gRPC Services

Use a gRPC client like [grpcurl](https://github.com/fullstorydev/grpcurl) or [BloomRPC](https://github.com/bloomrpc/bloomrpc) to test:

\`\`\`bash
# List services
grpcurl -plaintext localhost:${port} list

# Call a method
grpcurl -plaintext -d '{"id": "1"}' localhost:${port} user.UserService/GetUser
\`\`\`

## 🔧 Generate New Services

\`\`\`bash
# Generate a new gRPC service
struktos generate service product --type=grpc
\`\`\`

`;
  } else {
    readme += `The server will start at \`http://localhost:${port}\`

## 🔧 API Endpoints

- \`GET /\` - Welcome message
- \`GET /health\` - Health check

## 🔧 Generate New Entities

\`\`\`bash
# Generate a new entity with CRUD operations
struktos generate entity Product --fields="name:string,price:number"
\`\`\`

`;
  }

  readme += `## 📁 Project Structure

\`\`\`
${config.name}/
├── src/
│   ├── domain/           # Business entities & interfaces
│   ├── application/      # Use cases & application logic
│   ├── infrastructure/   # Adapters & external services
│   └── main.ts          # Application entry point
${isGrpc ? '├── protos/              # Protocol Buffer definitions\n' : ''}├── tests/
├── config/
└── package.json
\`\`\`

## 🏗️ Architecture

This project follows **Hexagonal Architecture** (Ports & Adapters):

- **Domain**: Core business logic, entities, repository interfaces
- **Application**: Use cases, application services
- **Infrastructure**: External adapters (${isGrpc ? 'gRPC' : 'HTTP'}, database, etc.)

## 🛠️ Scripts

| Script | Description |
|--------|-------------|
| \`npm run dev\` | Start development server with hot reload |
| \`npm run build\` | Build for production |
| \`npm start\` | Run production server |
`;

  if (config.persistence === 'postgresql') {
    readme += `| \`npm run db:generate\` | Generate Prisma client |
| \`npm run db:push\` | Push schema to database |
| \`npm run db:migrate\` | Run database migrations |
`;
  }

  if (config.useDocker) {
    readme += `
## 🐳 Docker

\`\`\`bash
# Build and run with Docker Compose
docker-compose up -d

# View logs
docker-compose logs -f app
\`\`\`
`;
  }

  readme += `
## 📄 License

MIT
`;

  return readme;
}